steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:latest'
      - '.'
    dir: 'backend'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:latest'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auto-structure-analysis-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '10'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'CORS_ORIGINS=https://johntfoster.github.io,http://localhost:5173'

images:
  - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/auto-structure-analysis-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
